### PR TITLE
refactor, feat: clean Cargo.toml files, upgrade tch to 0.10

### PR DESCRIPTION
**Pull request by ChefKissInc**
Adds support for Metal Performance Shaders to the Tch backend

### CODE REVIEW

**Review by nathanielsimard — CHANGES_REQUESTED** [review]
I would want to run the github action checks before merging, I think the github templates should be updated to trigger on `pull_request` instead of on `push`. It would be appreciated if you could update it so that we can test if it actually triggers for pull requests from public forks.

Otherwise great work and thank you for your contributions :smiley:

**Comment by ChefKissInc** [comment]
> I would want to run the github action checks before merging, I think the github templates should be updated to trigger on `pull_request` instead of on `push`. It would be appreciated if you could update it so that we can test if it actually triggers for pull requests from public forks.
> 
> Otherwise great work and thank you for your contributions 😃

Done

**Comment by ChefKissInc** [comment]
I also noticed a bunch of clippy warnings about inlining format arguments. I can send in another PR after this one to fix them if you'd like @nathanielsimard

**Comment by nathanielsimard** [comment]
> I also noticed a bunch of clippy warnings about inlining format arguments. I can send in another PR after this one to fix them if you'd like @nathanielsimard

Yes why not, but the CI is supposed to fail when there are clippy warnings. What command did you run?

**Comment by ChefKissInc** [comment]
> > I also noticed a bunch of clippy warnings about inlining format arguments. I can send in another PR after this one to fix them if you'd like @nathanielsimard
> 
> Yes why not, but the CI is supposed to fail when there are clippy warnings. What command did you run?

I'm actually on nightly rust, so the warnings may be new.
It's just cargo clippy

**Comment by ChefKissInc** [comment]
I've actually already fixed all the warnings except this
Screenshot 2022-12-25 at 17 37 40
At
Screenshot 2022-12-25 at 17 38 15

**Pull request merged**
