### PR TITLE
ci/Fix `cargo clippy` action

### PR DESCRIPTION
**Pull request by Luni-4**
### Checklist

- [x] Confirm that `run-checks` script has been executed.

### Related Issues/PRs

_Provide links to relevant issues and dependent PRs._

### Changes

This PR fixes the `clippy` action removing the filtering based on diff that does not always allow to detect clippy warnings

### Testing

_Describe how these changes have been tested._

### CODE REVIEW

**Comment by Luni-4** [comment]
@nathanielsimard 

This PR is ready to be reviewed

**Comment by Luni-4** [comment]
@nathanielsimard 

This PR is ready to be reviewd

**Comment by antimora** [comment]
I rebased and CI is still failing.

**Comment by Luni-4** [comment]
@antimora 

Yep, there are more clippy warnings to be fixed in the code

**Comment by Luni-4** [comment]
@antimora Rebased, but there are `clippy` warnings in tests

**Review by nathanielsimard — APPROVED** [review]
Thanks 🙏

**Pull request merged**
