### PR TITLE
Add cos, sin and tanh operations

### PR DESCRIPTION
**Pull request by makroiss**

### CODE REVIEW

**Review by nathanielsimard — COMMENTED** [review]
Very nice, the only thing missing are the tests.

You could add them in  `burn-tensor/src/tests/ops/*.rs` and register them in  `burn-tensor/src/tests/mod.rs` . This is similar for autodiff with `burn-autodiff/src/tests/*.rs` and `burn-autodiff/src/tests/mod.rs`. This way, tests will run on all backends.

Thanks a lot for your contribution!

**Comment by makroiss** [comment]
Thanks, I added the tests. Please double check the autodiff code

**Comment by nathanielsimard** [comment]
Everything seems fine now. I think the CI failure was caused by linting issues. Please update your fork by running the following commands:

```bash
cargo clippy --fix
cargo fmt --all
```

This should fix all issues.
Thanks again for your contribution. It's great work!

**Comment by makroiss** [comment]
Thanks for your help! updated the PR

**Review by nathanielsimard — APPROVED** [review]

**Pull request merged**
