### PR TITLE
bugfix for macos test

### PR DESCRIPTION
**Pull request by louisfd**
### Checklist

- [x] Confirm that `run-checks.sh` has been executed.

### Changes

Add patchy bugfix for MacOS bug in matmul continuous load vectorized

### CODE REVIEW

**Comment by antimora** [comment]
`test_matmul_tiling_2d_large_blocks` test has been fixed by there are other ones (see below is failing). 

These tests were enabled by @nathanielsimard using this line: `cargo test --features test-wgpu` in `run-checks.sh` script. @nathanielsimard , perhaps you can chime in? Is it because of a wrong device selected?


```
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.33s

Test burn-core with wgpu backend
   Compiling burn-core v0.8.0 (/Users/dilshod/Projects/burn/burn-core)
    Finished test [unoptimized + debuginfo] target(s) in 4.50s
     Running unittests src/lib.rs (/Users/dilshod/Projects/burn/target/debug/deps/burn_core-954e44a64d1a89cb)

running 80 tests
test lr_scheduler::noam::tests::test_function_increase_and_decrease ... ok
test data::dataloader::batch::tests::test_batch_dataloader ... ok
test data::dataloader::batch::tests::test_multi_thread_batch_dataloader ... ok
test nn::attention::mask::tests::test_generate_autoregressive_mask ... FAILED
test module::param::constant::tests::tensor_load_record_setting ... FAILED
test module::param::tensor::tests::test_load_record_setting ... FAILED
test nn::attention::mask::tests::test_generate_padding_mask ... FAILED
test grad_clipping::base::tests::test_clip_by_value ... FAILED
test grad_clipping::base::tests::test_clip_by_norm ... FAILED
test module::param::tensor::tests::test_init_with_record_setting ... FAILED
test nn::conv::conv1d::tests::configured_custom ... FAILED
test nn::attention::mha::tests::test_autoregressive_mask_should_have_same_output_as_autoregressive_decoding ... FAILED
test nn::dropout::tests::without_ad_backend_should_not_change_input ... FAILED
test nn::attention::mha::tests::test_generic_mha_shapes ... FAILED
test nn::attention::mha::tests::test_self_attention_mask_pad ... FAILED
test nn::attention::mha::tests::test_self_attention_shapes ... FAILED
test nn::conv::conv1d::tests::initializer_default ... FAILED
test nn::dropout::tests::with_ad_backend_should_mark_input ... FAILED
test nn::conv::conv1d::tests::initializer_zeros ... FAILED
test nn::conv::conv2d::tests::initializer_default ... FAILED
test nn::conv::conv2d::tests::initializer_zeros ... FAILED
test nn::embedding::tests::initializer_default ... FAILED
test nn::embedding::tests::initializer_zeros ... FAILED
test nn::initializer::tests::initializer_constant_init ... ok
test nn::initializer::tests::initializer_ones_init ... ok
test nn::initializer::tests::initializer_kaiming_uniform_init ... ok
test nn::initializer::tests::initializer_kaiming_uniform_init_fan_out ... ok
test nn::initializer::tests::initializer_zeros_init ... ok
test nn::linear::tests::initializer_default ... FAILED
test nn::linear::tests::initializer_zeros ... FAILED
test nn::linear::tests::test_linear_forward_no_bias ... FAILED
test nn::linear::tests::test_linear_forward_with_bias ... FAILED
test nn::loss::cross_entropy::tests::test_cross_entropy_loss ... FAILED
test nn::loss::cross_entropy::tests::test_cross_entropy_loss_with_pad_token ... FAILED
test nn::loss::mse::tests::test_mse_loss ... FAILED
test nn::initializer::tests::initializer_normal_init ... ok
test nn::norm::batch::tests_1d::batch_norm_forward_inference ... FAILED
test nn::norm::batch::tests_2d::batch_norm_forward_inference ... FAILED
test nn::norm::batch::tests_1d::batch_norm_forward_train ... FAILED
test nn::norm::batch::tests_2d::batch_norm_forward_train ... FAILED
test nn::norm::batch::tests_2d::batch_norm_grads ... FAILED
test nn::norm::batch::tests_2d::batch_norm_running_mean ... FAILED
test nn::norm::batch::tests_2d::batch_norm_running_mean_inner_module ... FAILED
test nn::norm::batch::tests_2d::batch_norm_running_var ... FAILED
test nn::norm::layer::tests::layer_norm_backward ... FAILED
test nn::norm::layer::tests::layer_norm_forward ... FAILED
test nn::pos_encoding::tests::test_generate_sinusoids ... FAILED
test nn::initializer::tests::initializer_kaiming_normal_init ... ok
test nn::rnn::gru::tests::tests_forward_single_input_single_feature ... FAILED
test nn::rnn::lstm::tests::test_forward_single_input_single_feature ... FAILED
test nn::rnn::lstm::tests::test_with_uniform_initializer ... FAILED
test nn::transformer::decoder::tests::test_autoregressive_norm_first ... FAILED
test nn::transformer::decoder::tests::test_autoregressive_norm_last ... FAILED
test nn::transformer::encoder::tests::test_autoregressive_norm_first ... FAILED
test nn::pos_encoding::tests::test_module ... FAILED
test nn::transformer::encoder::tests::test_autoregressive_norm_last ... FAILED
test optim::adam::tests::test_adam_optimizer_save_load_state ... FAILED
test optim::adam::tests::test_adam_optimizer_with_numbers ... FAILED
test optim::grad_accum::tests::test_accumulate_gradients_one_step ... FAILED
test optim::grad_accum::tests::test_accumulate_gradients_two_steps ... FAILED
test nn::initializer::tests::initializer_xavier_uniform_no_fan - should panic ... ok
test nn::initializer::tests::initializer_kaiming_uniform_init_bias ... ok
test optim::grads::tests::test_convert_grads ... FAILED
test nn::initializer::tests::initializer_uniform_init ... ok
test optim::sgd::tests::can_attach_gradient_clipping ... ok
test nn::initializer::tests::initializer_xavier_uniform_init ... ok
test optim::sgd::tests::should_load_state ... FAILED
test optim::sgd::tests::without_updated_params_should_not_have_state ... ok
test nn::initializer::tests::initializer_kaiming_uniform_no_fan - should panic ... ok
test optim::sgd::tests::with_updated_params_should_have_state ... FAILED
test record::file::tests::test_can_save_and_load_jsongz_format ... FAILED
test nn::pos_encoding::tests::input_length_should_be_less_than_max_len - should panic ... ok
test record::file::tests::test_can_save_and_load_bingz_format ... FAILED
test record::memory::tests::test_can_save_and_load_bin_format ... FAILED
test record::file::tests::test_can_save_and_load_mpkgz_format ... FAILED
test nn::pos_encoding::tests::d_model_input_should_match - should panic ... ok
test record::file::tests::test_can_save_and_load_pretty_json_format ... FAILED
test record::file::tests::test_can_save_and_load_bin_format ... FAILED
test record::recorder::tests::err_when_invalid_item - should panic ... ok
test nn::initializer::tests::initializer_xavier_normal_init ... ok

failures:

---- nn::attention::mask::tests::test_generate_autoregressive_mask stdout ----
thread 'nn::attention::mask::tests::test_generate_autoregressive_mask' panicked at 'No Integrated GPU device found, adapters [], other adapters []', burn-wgpu/src/context/base.rs:291:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- module::param::constant::tests::tensor_load_record_setting stdout ----
thread 'module::param::constant::tests::tensor_load_record_setting' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- module::param::tensor::tests::test_load_record_setting stdout ----
thread 'module::param::tensor::tests::test_load_record_setting' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::attention::mask::tests::test_generate_padding_mask stdout ----
thread 'nn::attention::mask::tests::test_generate_padding_mask' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- grad_clipping::base::tests::test_clip_by_value stdout ----
thread 'grad_clipping::base::tests::test_clip_by_value' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- grad_clipping::base::tests::test_clip_by_norm stdout ----
thread 'grad_clipping::base::tests::test_clip_by_norm' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- module::param::tensor::tests::test_init_with_record_setting stdout ----
thread 'module::param::tensor::tests::test_init_with_record_setting' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::conv::conv1d::tests::configured_custom stdout ----
thread 'nn::conv::conv1d::tests::configured_custom' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::attention::mha::tests::test_autoregressive_mask_should_have_same_output_as_autoregressive_decoding stdout ----
thread 'nn::attention::mha::tests::test_autoregressive_mask_should_have_same_output_as_autoregressive_decoding' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- nn::dropout::tests::without_ad_backend_should_not_change_input stdout ----
thread 'nn::dropout::tests::without_ad_backend_should_not_change_input' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::attention::mha::tests::test_generic_mha_shapes stdout ----
thread 'nn::attention::mha::tests::test_generic_mha_shapes' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- nn::attention::mha::tests::test_self_attention_mask_pad stdout ----
thread 'nn::attention::mha::tests::test_self_attention_mask_pad' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- nn::attention::mha::tests::test_self_attention_shapes stdout ----
thread 'nn::attention::mha::tests::test_self_attention_shapes' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- nn::conv::conv1d::tests::initializer_default stdout ----
thread 'nn::conv::conv1d::tests::initializer_default' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::dropout::tests::with_ad_backend_should_mark_input stdout ----
thread 'nn::dropout::tests::with_ad_backend_should_mark_input' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::conv::conv1d::tests::initializer_zeros stdout ----
thread 'nn::conv::conv1d::tests::initializer_zeros' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::conv::conv2d::tests::initializer_default stdout ----
thread 'nn::conv::conv2d::tests::initializer_default' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::conv::conv2d::tests::initializer_zeros stdout ----
thread 'nn::conv::conv2d::tests::initializer_zeros' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::embedding::tests::initializer_default stdout ----
thread 'nn::embedding::tests::initializer_default' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::embedding::tests::initializer_zeros stdout ----
thread 'nn::embedding::tests::initializer_zeros' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::linear::tests::initializer_default stdout ----
thread 'nn::linear::tests::initializer_default' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::linear::tests::initializer_zeros stdout ----
thread 'nn::linear::tests::initializer_zeros' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::linear::tests::test_linear_forward_no_bias stdout ----
thread 'nn::linear::tests::test_linear_forward_no_bias' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::linear::tests::test_linear_forward_with_bias stdout ----
thread 'nn::linear::tests::test_linear_forward_with_bias' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::loss::cross_entropy::tests::test_cross_entropy_loss stdout ----
thread 'nn::loss::cross_entropy::tests::test_cross_entropy_loss' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- nn::loss::cross_entropy::tests::test_cross_entropy_loss_with_pad_token stdout ----
thread 'nn::loss::cross_entropy::tests::test_cross_entropy_loss_with_pad_token' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- nn::loss::mse::tests::test_mse_loss stdout ----
thread 'nn::loss::mse::tests::test_mse_loss' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_1d::batch_norm_forward_inference stdout ----
thread 'nn::norm::batch::tests_1d::batch_norm_forward_inference' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_2d::batch_norm_forward_inference stdout ----
thread 'nn::norm::batch::tests_2d::batch_norm_forward_inference' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_1d::batch_norm_forward_train stdout ----
thread 'nn::norm::batch::tests_1d::batch_norm_forward_train' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_2d::batch_norm_forward_train stdout ----
thread 'nn::norm::batch::tests_2d::batch_norm_forward_train' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_2d::batch_norm_grads stdout ----
thread 'nn::norm::batch::tests_2d::batch_norm_grads' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_2d::batch_norm_running_mean stdout ----
thread 'nn::norm::batch::tests_2d::batch_norm_running_mean' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_2d::batch_norm_running_mean_inner_module stdout ----
thread 'nn::norm::batch::tests_2d::batch_norm_running_mean_inner_module' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::batch::tests_2d::batch_norm_running_var stdout ----
thread 'nn::norm::batch::tests_2d::batch_norm_running_var' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::layer::tests::layer_norm_backward stdout ----
thread 'nn::norm::layer::tests::layer_norm_backward' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::norm::layer::tests::layer_norm_forward stdout ----
thread 'nn::norm::layer::tests::layer_norm_forward' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::pos_encoding::tests::test_generate_sinusoids stdout ----
thread 'nn::pos_encoding::tests::test_generate_sinusoids' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::rnn::gru::tests::tests_forward_single_input_single_feature stdout ----
thread 'nn::rnn::gru::tests::tests_forward_single_input_single_feature' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::rnn::lstm::tests::test_forward_single_input_single_feature stdout ----
thread 'nn::rnn::lstm::tests::test_forward_single_input_single_feature' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::rnn::lstm::tests::test_with_uniform_initializer stdout ----
thread 'nn::rnn::lstm::tests::test_with_uniform_initializer' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::transformer::decoder::tests::test_autoregressive_norm_first stdout ----
thread 'nn::transformer::decoder::tests::test_autoregressive_norm_first' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::transformer::decoder::tests::test_autoregressive_norm_last stdout ----
thread 'nn::transformer::decoder::tests::test_autoregressive_norm_last' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/backend.rs:39:36

---- nn::transformer::encoder::tests::test_autoregressive_norm_first stdout ----
thread 'nn::transformer::encoder::tests::test_autoregressive_norm_first' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- nn::pos_encoding::tests::test_module stdout ----
thread 'nn::pos_encoding::tests::test_module' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/pool.rs:37:40

---- nn::transformer::encoder::tests::test_autoregressive_norm_last stdout ----
thread 'nn::transformer::encoder::tests::test_autoregressive_norm_last' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- optim::adam::tests::test_adam_optimizer_save_load_state stdout ----
thread 'optim::adam::tests::test_adam_optimizer_save_load_state' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- optim::adam::tests::test_adam_optimizer_with_numbers stdout ----
thread 'optim::adam::tests::test_adam_optimizer_with_numbers' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- optim::grad_accum::tests::test_accumulate_gradients_one_step stdout ----
thread 'optim::grad_accum::tests::test_accumulate_gradients_one_step' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- optim::grad_accum::tests::test_accumulate_gradients_two_steps stdout ----
thread 'optim::grad_accum::tests::test_accumulate_gradients_two_steps' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- optim::grads::tests::test_convert_grads stdout ----
thread 'optim::grads::tests::test_convert_grads' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- optim::sgd::tests::should_load_state stdout ----
thread 'optim::sgd::tests::should_load_state' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- optim::sgd::tests::with_updated_params_should_have_state stdout ----
thread 'optim::sgd::tests::with_updated_params_should_have_state' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- record::file::tests::test_can_save_and_load_jsongz_format stdout ----
thread 'record::file::tests::test_can_save_and_load_jsongz_format' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- record::file::tests::test_can_save_and_load_bingz_format stdout ----
thread 'record::file::tests::test_can_save_and_load_bingz_format' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- record::memory::tests::test_can_save_and_load_bin_format stdout ----
thread 'record::memory::tests::test_can_save_and_load_bin_format' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- record::file::tests::test_can_save_and_load_mpkgz_format stdout ----
thread 'record::file::tests::test_can_save_and_load_mpkgz_format' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- record::file::tests::test_can_save_and_load_pretty_json_format stdout ----
thread 'record::file::tests::test_can_save_and_load_pretty_json_format' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36

---- record::file::tests::test_can_save_and_load_bin_format stdout ----
thread 'record::file::tests::test_can_save_and_load_bin_format' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/dilshod/Projects/burn/burn-wgpu/src/ops/float_ops.rs:33:36


failures:
    grad_clipping::base::tests::test_clip_by_norm
    grad_clipping::base::tests::test_clip_by_value
    module::param::constant::tests::tensor_load_record_setting
    module::param::tensor::tests::test_init_with_record_setting
    module::param::tensor::tests::test_load_record_setting
    nn::attention::mask::tests::test_generate_autoregressive_mask
    nn::attention::mask::tests::test_generate_padding_mask
    nn::attention::mha::tests::test_autoregressive_mask_should_have_same_output_as_autoregressive_decoding
    nn::attention::mha::tests::test_generic_mha_shapes
    nn::attention::mha::tests::test_self_attention_mask_pad
    nn::attention::mha::tests::test_self_attention_shapes
    nn::conv::conv1d::tests::configured_custom
    nn::conv::conv1d::tests::initializer_default
    nn::conv::conv1d::tests::initializer_zeros
    nn::conv::conv2d::tests::initializer_default
    nn::conv::conv2d::tests::initializer_zeros
    nn::dropout::tests::with_ad_backend_should_mark_input
    nn::dropout::tests::without_ad_backend_should_not_change_input
    nn::embedding::tests::initializer_default
    nn::embedding::tests::initializer_zeros
    nn::linear::tests::initializer_default
    nn::linear::tests::initializer_zeros
    nn::linear::tests::test_linear_forward_no_bias
    nn::linear::tests::test_linear_forward_with_bias
    nn::loss::cross_entropy::tests::test_cross_entropy_loss
    nn::loss::cross_entropy::tests::test_cross_entropy_loss_with_pad_token
    nn::loss::mse::tests::test_mse_loss
    nn::norm::batch::tests_1d::batch_norm_forward_inference
    nn::norm::batch::tests_1d::batch_norm_forward_train
    nn::norm::batch::tests_2d::batch_norm_forward_inference
    nn::norm::batch::tests_2d::batch_norm_forward_train
    nn::norm::batch::tests_2d::batch_norm_grads
    nn::norm::batch::tests_2d::batch_norm_running_mean
    nn::norm::batch::tests_2d::batch_norm_running_mean_inner_module
    nn::norm::batch::tests_2d::batch_norm_running_var
    nn::norm::layer::tests::layer_norm_backward
    nn::norm::layer::tests::layer_norm_forward
    nn::pos_encoding::tests::test_generate_sinusoids
    nn::pos_encoding::tests::test_module
    nn::rnn::gru::tests::tests_forward_single_input_single_feature
    nn::rnn::lstm::tests::test_forward_single_input_single_feature
    nn::rnn::lstm::tests::test_with_uniform_initializer
    nn::transformer::decoder::tests::test_autoregressive_norm_first
    nn::transformer::decoder::tests::test_autoregressive_norm_last
    nn::transformer::encoder::tests::test_autoregressive_norm_first
    nn::transformer::encoder::tests::test_autoregressive_norm_last
    optim::adam::tests::test_adam_optimizer_save_load_state
    optim::adam::tests::test_adam_optimizer_with_numbers
    optim::grad_accum::tests::test_accumulate_gradients_one_step
    optim::grad_accum::tests::test_accumulate_gradients_two_steps
    optim::grads::tests::test_convert_grads
    optim::sgd::tests::should_load_state
    optim::sgd::tests::with_updated_params_should_have_state
    record::file::tests::test_can_save_and_load_bin_format
    record::file::tests::test_can_save_and_load_bingz_format
    record::file::tests::test_can_save_and_load_jsongz_format
    record::file::tests::test_can_save_and_load_mpkgz_format
    record::file::tests::test_can_save_and_load_pretty_json_format
    record::memory::tests::test_can_save_and_load_bin_format

test result: FAILED. 21 passed; 59 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass `--lib`
[burn]$ 

```

**Review by antimora — CHANGES_REQUESTED** [review]
The tests are still failing on Mac OS M1. Please see the comment above.

**Comment by antimora** [comment]
I think it's time we take care of CI testing on MacOS and Windows: https://github.com/burn-rs/burn/issues/428

**Comment by louisfd** [comment]
@antimora Thank you for pointing that out, it was indeed because the wrong device was selected for mac os. I had tested it locally on my mac and it worked, but forgot to run run-checks.sh. Here's a fix so that we use metal instead of vulkan when on mac os.

**Comment by antimora** [comment]
Thank you. I will test it as soon as I am in front of my computer.

**Review by antimora — APPROVED** [review]
I have tested on MacOS M1 and it's working as expected:

```

test tests::deserialize_with_new_field_order_works_with_pretty_json ... ok
test tests::deserialize_with_removed_constant_field_works_with_pretty_json ... ok
test tests::deserialize_with_new_optional_field_works_with_pretty_json ... ok
test tests::deserialize_with_removed_optional_field_works_with_pretty_json ... ok

test result: ok. 15 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s

   Doc-tests burn-core

running 1 test
test src/module/base.rs - module::base::Module (line 75) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.32s

Script executed in 139 seconds.
[burn]$ 
```

**Pull request merged**
