### PR TITLE
Hide crate name in onnx-import crate and onnx-inference example

### PR DESCRIPTION
**Pull request by Luni-4**
### Checklist

- [x] Confirm that `run-checks.sh` has been executed.

### Related Issues/PRs

_Provide links to relevant issues and dependent PRs._

### Changes

I have changed the `burn-import` crate `README` and the `onnx-inference` example such that the crate name stays hidden, making the code clearer and less error prone for new users.

### Testing

Run `cargo build` on `onnx-inference` crate.

### CODE REVIEW

**Review by antimora — APPROVED** [review]
Thank you. Looks good.

**Comment by Luni-4** [comment]
Thanks to you @antimora for your review! 

Yep, it seems to fail for new clippy warnings.

Just wondering, is this [lib.rs](https://github.com/burn-rs/burn/blob/main/examples/onnx-inference/src/lib.rs) necessary for the example, because it might be misleading for a new beginner in my opinion.

**Comment by antimora** [comment]
Fixed the failing CI in this PR: https://github.com/burn-rs/burn/pull/494

**Comment by Luni-4** [comment]
Rebased!

@antimora 

Ok, I see, thanks for your clarification! I'm most used to the `bin` folder and `lib.rs` approach, but it's the same using the `main.rs' file.

**Review by nathanielsimard — APPROVED** [review]

**Comment by nathanielsimard** [comment]
@Luni-4 It seems like there is a remaining issue with the CI. Once it's resolved, I'll be able to merge.

**Comment by antimora** [comment]
we will have to fix in burn-import by allowing dead code on the new and init with. Previously probably the main code wasn't building. 

Let me look into this.

**Comment by antimora** [comment]
OK. I have fixed the CI issue. @nathanielsimard, it's ready to be merged.

**Comment by Luni-4** [comment]
Oh, thank you for spotting the warning! Even though it's strange because that constant was used in the code

**Pull request merged**
